// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjv8yqsHkFKHcxeD7_0DXntRkccuGnfMo',
    appId: '1:901847529972:web:8583c23232f2dd7b46a1a1',
    messagingSenderId: '901847529972',
    projectId: 'mental-health1',
    authDomain: 'mental-health1.firebaseapp.com',
    storageBucket: 'mental-health1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAriW7EDGwmy7N1Ns889Xd8Ty23pa4PXtk',
    appId: '1:901847529972:android:89731e9445ba646046a1a1',
    messagingSenderId: '901847529972',
    projectId: 'mental-health1',
    storageBucket: 'mental-health1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF0_I--ZkjSzJvHHJn80CHkx7tVYN88zE',
    appId: '1:901847529972:ios:4ddf8a724668ac6346a1a1',
    messagingSenderId: '901847529972',
    projectId: 'mental-health1',
    storageBucket: 'mental-health1.appspot.com',
    iosBundleId: 'com.example.projectc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF0_I--ZkjSzJvHHJn80CHkx7tVYN88zE',
    appId: '1:901847529972:ios:4ddf8a724668ac6346a1a1',
    messagingSenderId: '901847529972',
    projectId: 'mental-health1',
    storageBucket: 'mental-health1.appspot.com',
    iosBundleId: 'com.example.projectc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjv8yqsHkFKHcxeD7_0DXntRkccuGnfMo',
    appId: '1:901847529972:web:a96e23c5f2e52cdd46a1a1',
    messagingSenderId: '901847529972',
    projectId: 'mental-health1',
    authDomain: 'mental-health1.firebaseapp.com',
    storageBucket: 'mental-health1.appspot.com',
  );

}